//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGAdmin
    {
        public int Id { get; set; }
        public string AdminPwd { get; set; }
        public string NoticiasBanner { get; set; }
        public string SponsorsBanner { get; set; }
        public string IntegrantesBanner { get; set; }
        public string Institucional { get; set; }
    }
}
