//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FGEntities : DbContext
    {
        public FGEntities()
            : base("name=FGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FGAdmin> FGAdmins { get; set; }
        public virtual DbSet<Integrante> Integrantes { get; set; }
        public virtual DbSet<Carrusel> Carrusels { get; set; }
        public virtual DbSet<Publicidad> Publicidads { get; set; }
        public virtual DbSet<Sponsor> Sponsors { get; set; }
        public virtual DbSet<Noticia> Noticias { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
