//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integrante
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Foto { get; set; }
        public string Nick { get; set; }
        public string Email { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public string YouTubeLink { get; set; }
        public string Divisiones { get; set; }
        public string TwitchTVLink { get; set; }
    }
}
