//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int Id { get; set; }
        public string Volanta { get; set; }
        public string Titulo { get; set; }
        public string Subtitulo { get; set; }
        public string ImagenPortada { get; set; }
        public string Pie { get; set; }
        public string Cuerpo { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string ImagenNoticia { get; set; }
    }
}
