//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicidad
    {
        public int Id { get; set; }
        public string Banner { get; set; }
        public string Url { get; set; }
    }
}
