//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int Id { get; set; }
        public string LogoBarra { get; set; }
        public string Titulo { get; set; }
        public string Url { get; set; }
        public string FacebookUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string Descripcion { get; set; }
        public int Orden { get; set; }
        public string LogoPagina { get; set; }
    }
}
