//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquiaIT.Models.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public int ClientID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Area { get; set; }
        public string TelephoneNumber { get; set; }
        public string InternNumber { get; set; }
        public string email { get; set; }
        public bool Active { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
