//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquiaIT.Models.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Spends = new HashSet<Spend>();
            this.Retentions = new HashSet<Retention>();
        }
    
        public int Id { get; set; }
        public int POLineID { get; set; }
        public int CategoryID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal ValueInPesos { get; set; }
        public Nullable<decimal> ValueInDollars { get; set; }
        public decimal IVA { get; set; }
        public Nullable<decimal> ChangeRate { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
    
        public virtual InvoiceCategory InvoiceCategory { get; set; }
        public virtual PurchaseOrderLine PurchaseOrderLine { get; set; }
        public virtual InvoiceStatus InvoiceStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spend> Spends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retention> Retentions { get; set; }
    }
}
