//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquiaIT.Models.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retention
    {
        public int Id { get; set; }
        public int InvoiceID { get; set; }
        public decimal Ganancias { get; set; }
        public decimal IVA { get; set; }
        public decimal SUSS { get; set; }
        public decimal IIBB { get; set; }
        public decimal IIBBSpends { get; set; }
        public decimal Others { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
