//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquiaIT.Models.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spend
    {
        public int Id { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string Vendor { get; set; }
        public string Description { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<decimal> POValueInDollars { get; set; }
        public Nullable<decimal> InvoiveValueInDollars { get; set; }
        public decimal InvoiceValue { get; set; }
        public decimal IVA { get; set; }
        public Nullable<decimal> IIBB_ARBA { get; set; }
        public Nullable<decimal> ARC_IVA { get; set; }
        public decimal InvoiceTotal { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
